# Site settings
title: APK Station
email: your-email@example.com
description: A simple website to host APK files
baseurl: "/apk-station" # the subpath of your site, e.g. /blog
url: "https://hike-projects.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Permalink structure
permalink: /:categories/:title/

# Jekyll SEO tag settings (optional, but recommended for SEO)
jekyll_seo_tag:
  social: 
    name: "APK Station"
    image: "/assets/images/logo.png"  # Example: Path to your site's logo

# Pagination settings (optional)
pagination:
  enabled: true
  per_page: 10
  paginate_path: "/page:num/"
  layout: default

# Exclude from processing
exclude:
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock

# Include additional files
include:
  - _config.yml

# Optional settings for plugins
kramdown:
  input: GFM
  hard_wrap: false

# Default metadata for your site
defaults:
  -
    scope:
      path: ""  # Empty string applies to all files
    values:
      layout: default
      author: yourname  # Default author name
