# Site settings
title: APK Station
description: A simple website to host APK files
url: "https://yourusername.github.io" # Replace with the correct URL
baseurl: "/apk-station" # Subpath of the repository

# Build settings
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Collections (Define once for custom collections like `apks`)
collections:
  apks:
    output: true # Enables generation of pages for this collection

# Permalinks
permalink: /:collection/:name/

# Defaults (Global metadata for all files)
defaults:
  - scope:
      path: "" # Applies to all files
    values:
      layout: default
      author: APK Station

# Exclude unnecessary files from being processed by Jekyll
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor
