# Site settings
title: APK Station
description: A simple website to host APK files
url: "https://hike-projects.github.io" # Base URL for your GitHub Pages site
baseurl: "/apk-station" # Subpath of your repository

# Build settings
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Disable default post collections
collections:
  posts:
    output: false

# Permalink structure
permalink: /:name/

# Defaults for all files
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
collections:
  apks:
    output: true
permalink: /:collection/:name/
